---
title: Complejo.java
---
classDiagram
  class Complejo {
    - double real
    - double i
    - double modulo

    + Complejo()
    + Complejo(double real, double i)
    + toString() String
    + equals(Complejo c) boolean
    + compareTo(Complejo c) boolean
    - modulo() double
    + suma() Complejo
    + resta() Complejo
    + multiplica() Complejo
    + divide() Complejo
  }